const petsData = [
  {
    id: 1,
    name: '糯米',
    category: 'cat',
    breed: '英国短毛猫',
    emoji: '😺',
    imageUrl: 'https://cdn.pixabay.com/photo/2015/06/19/14/09/cat-815199_640.jpg',
    bgColor: '#e8d5c4',
    price: 3800,
    badge: '热门',
    traits: ['温顺', '亲人', '好养'],
    desc: '纯种英国短毛猫，圆脸大眼睛，性格温顺安静。已接种疫苗，会使用猫砂盆，适合新手家庭。',
    gender: '公',
    age: '3个月'
  },
  {
    id: 2,
    name: '布丁',
    category: 'cat',
    breed: '布偶猫',
    emoji: '😸',
    imageUrl: 'https://cdn.pixabay.com/photo/2023/02/01/17/48/cat-7759260_1280.jpg',
    bgColor: '#d4c4f2',
    price: 6800,
    badge: '精选',
    traits: ['粘人', '温柔', '颜值高'],
    desc: '双色布偶猫，蓝眼睛，性格极其粘人温柔。已接种两针疫苗，社会化训练完成。',
    gender: '母',
    age: '4个月'
  },
  {
    id: 3,
    name: '团子',
    category: 'dog',
    breed: '柯基犬',
    emoji: '🐕',
    imageUrl: 'https://cdn.pixabay.com/photo/2022/03/24/13/21/corgi-7085814_1280.jpg',
    bgColor: '#f2d5c4',
    price: 5200,
    badge: null,
    traits: ['活泼', '聪明', '短腿萌'],
    desc: '彭布罗克威尔士柯基犬，三色花色。性格开朗活泼，已学会基本指令，适合有孩子的家庭。',
    gender: '公',
    age: '3个月'
  },
  {
    id: 4,
    name: '豆豆',
    category: 'dog',
    breed: '金毛寻回犬',
    emoji: '🐶',
    imageUrl: 'https://cdn.pixabay.com/photo/1552053831-71594a276ef1_1280.jpg',
    bgColor: '#c4d7f2',
    price: 4500,
    badge: '推荐',
    traits: ['忠诚', '友善', '聪明'],
    desc: '纯种金毛寻回犬，浅金色被毛。性格温顺友善，智商极高，是理想的家庭伴侣犬。',
    gender: '母',
    age: '4个月'
  },
  {
    id: 5,
    name: '奶盖',
    category: 'cat',
    breed: '异国短毛猫',
    emoji: '😻',
    imageUrl: 'https://cdn.pixabay.com/photo/2014/11/30/14/11/cat-555758_1280.jpg',
    bgColor: '#d4c4f2',
    price: 5500,
    badge: null,
    traits: ['呆萌', '安静', '懒洋洋'],
    desc: '加菲猫（异国短毛猫），扁脸大眼，表情呆萌可爱。性格安静不闹腾，适合公寓饲养。',
    gender: '公',
    age: '3个月'
  },
  {
    id: 6,
    name: '毛球',
    category: 'small',
    breed: '荷兰垂耳兔',
    emoji: '🐰',
    imageUrl: 'https://cdn.pixabay.com/photo/2018/08/15/22/41/rabbit-3611792_1280.jpg',
    bgColor: '#f2e6d3',
    price: 880,
    badge: '入门',
    traits: ['可爱', '温顺', '好打理'],
    desc: '纯种荷兰垂耳兔，毛色雪白，耳朵自然下垂。性格温顺，已习惯被人抱抱。',
    gender: '公',
    age: '2个月'
  },
  {
    id: 7,
    name: '雪糕',
    category: 'dog',
    breed: '比熊犬',
    emoji: '🐩',
    imageUrl: 'https://cdn.pixabay.com/photo/2021/04/12/18/34/bichon-6169975_1280.jpg',
    bgColor: '#e8e0f2',
    price: 4200,
    badge: null,
    traits: ['不掉毛', '黏人', '小巧'],
    desc: '纯种比熊犬，毛发蓬松如棉花糖。性格活泼可爱，不掉毛，适合过敏体质的主人。',
    gender: '母',
    age: '4个月'
  },
  {
    id: 8,
    name: '琥珀',
    category: 'cat',
    breed: '橘猫',
    emoji: '🐱',
    imageUrl: 'https://cdn.pixabay.com/photo/2014/10/01/17/45/cat-468230_1280.jpg',
    bgColor: '#f2d5a0',
    price: 1800,
    badge: '性价比',
    traits: ['贪吃', '亲人', '皮实'],
    desc: '中华田园橘猫，虎斑纹，圆脸大眼。性格亲人爱蹭蹭，身体棒好养活。',
    gender: '公',
    age: '3个月'
  },
  {
    id: 9,
    name: '芝麻',
    category: 'small',
    breed: '龙猫',
    emoji: '🐹',
    imageUrl: 'https://cdn.pixabay.com/photo/1508933820087-4b84fb60a898_1280.jpg',
    bgColor: '#d4d4d4',
    price: 1500,
    badge: null,
    traits: ['安静', '好养', '软萌'],
    desc: '标准灰色龙猫，毛发柔软如丝绒。性格温顺，夜行性动物，适合白天上班的饲主。',
    gender: '母',
    age: '4个月'
  }
];
